### ISSUE TITLE
KeyError: 'pgmap'

### ISSUE THREAD

**Issue by jcea** [ceph/python-crush#4]
Running Ceph 12.2.5, crush 1.0.35 (current PyPI version).

Following documentation at https://crush.readthedocs.io/en/latest/ceph/optimize.html#how-to-rebalance-a-pool-step-by-step

```
$ ceph report > report.json
report 273333295
$ crush optimize \
        --step 1 \
        --crushmap report.json --out-path optimized.crush \
        --pool 3
Traceback (most recent call last):
  File "/usr/local/bin/crush", line 25, in <module>
    sys.exit(Ceph().main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/crush/main.py", line 136, in main
    return self.constructor(argv).run()
  File "/usr/local/lib/python2.7/dist-packages/crush/optimize.py", line 378, in run
    crushmap = self.main.convert_to_crushmap(self.args.crushmap)
  File "/usr/local/lib/python2.7/dist-packages/crush/ceph/__init__.py", line 776, in convert_to_crushmap
    c.parse(crushmap)
  File "/usr/local/lib/python2.7/dist-packages/crush/__init__.py", line 138, in parse
    return self.parse_crushmap(self._convert_to_crushmap(something))
  File "/usr/local/lib/python2.7/dist-packages/crush/ceph/__init__.py", line 447, in _convert_to_crushmap
    crushmap = CephReport().parse_report(something)
  File "/usr/local/lib/python2.7/dist-packages/crush/ceph/__init__.py", line 73, in parse_report
    for pg_stat in report['pgmap']['pg_stats']:
KeyError: 'pgmap'
```

Other subcommands like "analyze" fails too.

**Comment by hnuzhoulin** [comment]
same problem.seems the output of ceph_report changed much in 12.2.5 .
ceph report does not contain pg infomation

**Comment by xelexin** [comment]
12.2.4 this same error

**Comment by caisan** [comment]
13.2.2 same error

**Comment by brushek** [comment]
on 12.2.9 there is the same problem

**Comment by rushikeshjadhav** [comment]
same problem for 14.2.4
