### ISSUE TITLE
some mapping failed

### ISSUE THREAD

**Issue by hnuzhoulin** [ceph/python-crush#5]
Running Ceph 12.2.5, crush 1.0.35 (current PyPI version).

default ceph report does not have information about pg,so I using 

```
ceph pg dump -f json > pg_dump.json
# edit crush/ceph/__init__.py,add line 72
report['pgmap'] = json.load(open('pg_dump.json'))
# replace crush_ruleset with crush_rule in line 115
ruleset = pool['crush_rule']
```

and then output is:

```
2018-07-16 16:35:04,999 42.7e map to [32, 320, 144] instead of [32, 320, 167]
2018-07-16 16:35:04,999 42.73 map to [134, 295, 144] instead of [134, 295, 196]
2018-07-16 16:35:05,000 43.57 map to [21, 416, 144] instead of [21, 416, 185]
2018-07-16 16:35:05,004 44.87 map to [41, 144, 314] instead of [41, 314]
2018-07-16 16:35:05,005 44.7d map to [144, 371, 34] instead of [227, 371, 34]
2018-07-16 16:35:05,006 45.f2 map to [144, 414, 48] instead of [237, 414, 48]
2018-07-16 16:35:05,007 45.46 map to [144, 336, 14] instead of [234, 336, 14]
2018-07-16 16:35:05,008 46.45 map to [361, 144, 47] instead of [361, 256, 47]
2018-07-16 16:35:05,008 46.65 map to [144, 377, 23] instead of [218, 377, 23]
```

**Comment by goldyfruit** [comment]
Same issue here.
```
crush analyze --crushmap ceph_report.json --pool 27 
Traceback (most recent call last):
  File "/usr/local/bin/crush", line 25, in <module>
    sys.exit(Ceph().main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/crush/main.py", line 136, in main
    return self.constructor(argv).run()
  File "/usr/local/lib/python2.7/dist-packages/crush/analyze.py", line 400, in run
    return self.analyze_report(*self.analyze())
  File "/usr/local/lib/python2.7/dist-packages/crush/analyze.py", line 372, in analyze
    c.parse(self.main.convert_to_crushmap(self.args.crushmap))
  File "/usr/local/lib/python2.7/dist-packages/crush/ceph/__init__.py", line 776, in convert_to_crushmap
    c.parse(crushmap)
  File "/usr/local/lib/python2.7/dist-packages/crush/__init__.py", line 138, in parse
    return self.parse_crushmap(self._convert_to_crushmap(something))
  File "/usr/local/lib/python2.7/dist-packages/crush/ceph/__init__.py", line 447, in _convert_to_crushmap
    crushmap = CephReport().parse_report(something)
  File "/usr/local/lib/python2.7/dist-packages/crush/ceph/__init__.py", line 114, in parse_report
    ruleset = pool['crush_ruleset']
KeyError: 'crush_ruleset'
```
